version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: taskdef.json
        LoadBalancerInfo:
          ContainerName: node-js
          ContainerPort: 3000
